name: Publish Extension

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run compile

      - name: Install Open VSX CLI
        run: npm install -g ovsx

      - name: Publish to Open VSX
        run: ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}
